[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_8MB.csv

; Исправленные библиотеки - CC1101 берём с GitHub
lib_deps = 
    bodmer/TFT_eSPI@^2.5.33
    crankyoldgit/IRremoteESP8266@^2.8.6
    nrf24/RF24@^1.4.8
    https://github.com/LSatan/SmartRC-CC1101-Driver-Lib.git

build_flags = 
    -D USER_SETUP_LOADED
    -D ST7789_DRIVER
    -D TFT_WIDTH=135
    -D TFT_HEIGHT=240
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=13
    -D TFT_RST=14
    -D TFT_BL=15
    -D TFT_RGB_ORDER=TFT_RGB
    -D TFT_INVERSION_ON
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D SPI_FREQUENCY=40000000
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
